### PR TITLE
Update to amethyst 0.12

### PR DESCRIPTION
**Pull request by AnneKitsune**

### CODE REVIEW

**Review by topokel — APPROVED** [review]

**Comment by topokel** [comment]
We have bors now? neat

bors r+

**Comment by topokel** [comment]
I'm too dumb to know what that means.

**Comment by cosmicspacedragon** [comment]
Have you tried checking here?
image

**Comment by AnneKitsune** [comment]
/shrug

Doesn't seem to have the logs as to what timed out :/

**Pull request merged**
