### PR TITLE
Upgrade specs-physics to latest nphysics

### PR DESCRIPTION
**Pull request by willcrichton**
Since #23 seems to have stagnated, I went ahead and updated specs-physics to the latest nalgebra/nphysics versions. It passes all the tests in the repo, but I haven't attempted a larger integration into Amethyst yet.

### CODE REVIEW

**Comment by sapphire-arches** [comment]
It looks like there's a slightly newer version of n{physics,collide,algebra} available, and upgrading to those doesn't break the build at least:

```diff
diff --git a/Cargo.toml b/Cargo.toml
index 8baa02c..b547f0c 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -20,12 +20,12 @@ amethyst = ["amethyst_core"]
 
 [dependencies]
 log = "0.4.6"
 specs = "0.16.0"
 specs-hierarchy = "0.6.0"
 shrev = "1.1.1"
-nalgebra = "0.19.0"
-ncollide3d = "0.21.0"
-nphysics3d = "0.13.1"
+nalgebra = "0.20"
+ncollide3d = "0.22"
+nphysics3d = "0.14"
 amethyst_core = { git = "https://github.com/amethyst/amethyst", optional = true }
 objekt = "0.1.2"
 
```

**Comment by sapphire-arches** [comment]
That does end up pulling in a different version of nalgebra from what crates.io Amethyst is currently using unfortunately, so maybe it's not the best idea to integrate it into this PR.

**Comment by willcrichton** [comment]
That's right, I specifically chose the n* crate versions for compatibility with Amethyst.

**Review by AnneKitsune — APPROVED** [review]
Thanks!

**Comment by AnneKitsune** [comment]
bors r+

```
     Running target/debug/deps/specs_physics-7d8561ffccc4c3d0

running 3 tests
test systems::sync_colliders_to_physics::tests::add_collider ... ok
test systems::sync_bodies_to_physics::tests::add_rigid_body ... ok
test systems::sync_parameters_to_physics::tests::update_gravity ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests specs-physics

running 8 tests
test src/lib.rs -  (line 217) ... ok
test src/lib.rs -  (line 44) ... ok
test src/lib.rs -  (line 88) ... ok
test src/bodies.rs - bodies::PhysicsBodyBuilder (line 149) ... ok
test src/colliders.rs - colliders::PhysicsColliderBuilder (line 211) ... ok
test src/lib.rs -  (line 113) ... ok
test src/lib.rs -  (line 168) ... ok
test src/lib.rs - physics_dispatcher (line 400) ... ok

test result: ok. 8 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

**Pull request merged**
