### PR TITLE
Update specs

### PR DESCRIPTION
**Pull request by cedric-h**
Unfortunately, the amethyst test fails, but I believe that's because all of amethyst isn't using specs 0.15.0 yet. I'm sure they will be soon though, because the new API is much more ergonomic, you don't have to register components anymore. I went ahead and updated specs-hierarchy to specs 0.15.0, when they accept my PR I'll update the Cargo.toml to look there instead of on my fork of the github. I just don't think it would be feasible for me to do that for all of amethyst! :grin:

### CODE REVIEW

**Comment by cedric-h** [comment]
My specs-hierarchy PR merged, so that's updated now. Once it's on crates.io I'll update these commits to pull from there instead of my git fork.

**Comment by topokel** [comment]
I'll target to merge this once the next version of Amethyst is released.

**Comment by ChrisPWill** [comment]
@distransient Out of curiosity, is there any plan to decouple this library from Amethyst? If so, I'd be happy to help with this effort. I love specs, but I have no need for the full Amethyst framework, so having access to the latest features would be nice without having to wait for Amethyst.

Apologies if this has been asked before or if this seems like a stupid question.

**Comment by topokel** [comment]
The API is not at all coupled to Amethyst. You can easily use specs-physics without Amethyst, all you have to do is nothing, since the amethyst code is not enabled by default.

**Comment by ChrisPWill** [comment]
Apologies, after posting my comment I went and read through the code (should have done this in the first place) and so I now understand how the amethyst code works. I wasn't asking about the API, by the way, I was asking about the library itself. Because this PR is blocked by Amethyst, I see the library (or at least its pace of development) being coupled to Amethyst.

Regardless, I was out of line. There's nothing stopping me from making my own fork with these changes merged.

**Review by topokel — APPROVED** [review]

**Comment by topokel** [comment]
Merged via #21! (used that to push my conflict fixes)

**Pull request closed without merging**
